Name:           ros-indigo-orogen
Version:        2.8.0
Release:        0%{?dist}
Summary:        ROS orogen package

Group:          Development/Libraries
License:        GPL v2 or later
URL:            http://rock-robotics.org/documentation/orogen
Source0:        %{name}-%{version}.tar.gz

Requires:       openssl-devel
Requires:       ros-indigo-catkin
Requires:       ros-indigo-metaruby
Requires:       ros-indigo-rtt
Requires:       ros-indigo-rtt-typelib
Requires:       ros-indigo-typelib
Requires:       ros-indigo-utilrb
Requires:       ruby
Requires:       ruby-devel
Requires:       rubygem-nokogiri
Requires:       rubygem-rake
Requires:       rubygem-rake-compiler
Requires:       rubygems
BuildRequires:  cmake
BuildRequires:  openssl-devel
BuildRequires:  ruby
BuildRequires:  ruby-devel
BuildRequires:  rubygems

%description
orogen offers a specification interface for components developped in the Orocos
Realtime Toolkit. Moreover, it generates the specified modules, thus offering an
easy and fast development process.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Jan 26 2015 OCL Development Team <orocos-dev@lists.mech.kuleuven.be> - 2.8.0-0
- Autogenerated by Bloom

